---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-client
  labels:
    app: alpine-client
  annotations:
    networkservicemesh.io: kernel://ipfilter-service/nsm-1
spec:
  nodeSelector:
    kubernetes.io/hostname: node01
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]